// <auto-generated />
using BookLibraryProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookLibraryProject.Migrations
{
    [DbContext(typeof(LibraryContext))]
    [Migration("20250830160431_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookLibraryProject.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Category")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CopiesInUse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ISBN")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TotalCopies")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Category = "Fiction",
                            CopiesInUse = 1,
                            FirstName = "J.D.",
                            ISBN = "0123456789",
                            LastName = "Salinger",
                            Title = "The Catcher in the Rye",
                            TotalCopies = 10,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 2,
                            Category = "Fiction",
                            CopiesInUse = 2,
                            FirstName = "Harper",
                            ISBN = "0987654321",
                            LastName = "Lee",
                            Title = "To Kill a Mockingbird",
                            TotalCopies = 8,
                            Type = "Paperback"
                        },
                        new
                        {
                            BookId = 3,
                            Category = "Dystopian Fiction",
                            CopiesInUse = 5,
                            FirstName = "George",
                            ISBN = "1122334455",
                            LastName = "Orwell",
                            Title = "1984",
                            TotalCopies = 15,
                            Type = "Hardcover"
                        },
                        new
                        {
                            BookId = 4,
                            Category = "Programming",
                            CopiesInUse = 1,
                            FirstName = "Robert C.",
                            ISBN = "5566778899",
                            LastName = "Martin",
                            Title = "Clean Code",
                            TotalCopies = 5,
                            Type = "Paperback"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
